# Implement Eigen values, Eigen Vectors, Rank , SVD , nullity

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
from scipy.linalg import svd

## Eigen values and vectors


In [4]:
a=np.matrix('5 8 16; 4 1 8; -4 -4 -11')
a

matrix([[  5,   8,  16],
        [  4,   1,   8],
        [ -4,  -4, -11]])

In [5]:
values,vectors=eig(a)
print(vectors)
print()
print(values)

[[-0.81649658+0.j         -0.31924166+0.43269619j -0.31924166-0.43269619j]
 [-0.40824829+0.j          0.78143831+0.j          0.78143831-0.j        ]
 [ 0.40824829+0.j         -0.23109832-0.2163481j  -0.23109832+0.2163481j ]]

[ 1.+0.00000000e+00j -3.+1.46298053e-15j -3.-1.46298053e-15j]


In [6]:
a=np.matrix('8 -8 -2; 4 -3 -2; 3 -4 1')
a

matrix([[ 8, -8, -2],
        [ 4, -3, -2],
        [ 3, -4,  1]])

In [7]:
values,vectors=eig(a)
print(vectors)
print()
print(values)

[[-0.74278135 -0.81649658 -0.80178373]
 [-0.55708601 -0.40824829 -0.53452248]
 [-0.37139068 -0.40824829 -0.26726124]]

[1. 3. 2.]


## SVD

In [9]:
a=np.matrix([-1,2,2])
a

matrix([[-1,  2,  2]])

In [10]:
a.T

matrix([[-1],
        [ 2],
        [ 2]])

In [11]:
U, s, VT = svd(a.T)
print(U)
print(s)
print(VT)

[[-0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.66666667 -0.33333333]
 [ 0.66666667 -0.33333333  0.66666667]]
[3.]
[[1.]]


## Rank and nullity

In [12]:
from sympy import Matrix

A = [[1,-3,-2,4], [1,-3,1,1], [0,0,-1,1]]

A = Matrix(A)

# Number of Columns
NoC = A.shape[1]

# Rank of A
rank = A.rank()

# Nullity of the Matrix
nullity = NoC - rank

print("Nullity : ", nullity)
print("Rank : ",rank)

Nullity :  2
Rank :  2
