In [1]:
import pandas as pd
import seaborn as sns
import numpy as np 


In [6]:
a={'x':[1,2,3,4,5],'y':[2,4,5,4,5]}

In [3]:
a

{'x': [1, 2, 3, 4, 5], 'y': [2, 4, 5, 4, 5]}

In [7]:
df=pd.DataFrame(a)

In [10]:
df

x  y
0  1  2
1  2  4
2  3  5
3  4  4
4  5  5

In [8]:
A=np.array(df)

In [9]:
a

{'x': [1, 2, 3, 4, 5], 'y': [2, 4, 5, 4, 5]}

In [28]:
# calculate the mean of each column
M = np.mean(A.T, axis=1)
print("Mean of Columns")
print(M)

Mean of Columns
[3.5        4.16666667]


In [29]:
# center columns by subtracting column means
C = A - M
print(C)

[[-2.5        -2.16666667]
 [-1.5        -0.16666667]
 [-0.5         0.83333333]
 [ 0.5        -0.16666667]
 [ 1.5         0.83333333]
 [ 2.5         0.83333333]]


In [31]:
print("calculate covariance matrix of centered matrix")
V = np.cov(C.T)
print(V)

calculate covariance matrix of centered matrix
[[3.5        1.7       ]
 [1.7        1.36666667]]


In [56]:
v=1.7 #covariance


In [44]:
variance=C**2

In [51]:
variance[:,0]

array([6.25, 2.25, 0.25, 0.25, 2.25, 6.25])

In [53]:
sum_x =sum(variance[:,0]) 

In [54]:
sum_x

17.5

In [57]:
m= v/sum_x

In [58]:
m

0.09714285714285714

In [59]:
#c=y_mean - m*x_mean
c= 4.1- m*3.5

In [60]:
c

3.76

In [ ]:
#y=mx+c
#y=0.0971x + 3.76

In [62]:
y=m*5+c #[x=5]
y

4.2457142857142856

In [84]:
for i in range(df['x'].iloc[0]):
    y_pred= m*df['x']+c

In [85]:
y_pred

0    3.857143
1    3.954286
2    4.051429
3    4.148571
4    4.245714
5    4.342857
Name: x, dtype: float64

In [78]:
df['x']

0    1
1    2
2    3
3    4
4    5
5    6
Name: x, dtype: int64

In [87]:
y_y_diff=df['y']-y_pred

In [88]:
y_y_diff

0   -1.857143
1    0.045714
2    0.948571
3   -0.148571
4    0.754286
5    0.657143
dtype: float64

In [90]:
e=y_y_diff**2

In [91]:
e

0    3.448980
1    0.002090
2    0.899788
3    0.022073
4    0.568947
5    0.431837
dtype: float64

In [92]:
sse=sum(e)

In [93]:
sse

5.373714285714285

In [94]:
mse=sse/6

In [95]:
mse

0.8956190476190474

In [97]:
rmse= mse**1/2

In [98]:
rmse

0.4478095238095237

In [120]:
mid_tss=C[:,1]

In [126]:
tss_a=mid_tss**2
tss=sum(tss_a)
tss

6.833333333333332

In [129]:
R_square= 1-sse/tss

In [130]:
R_square

0.213602787456446

In [132]:
y=m*10+c
y

4.731428571428571

In [133]:
a={'x':[95,85,80,70,60],'y':[85,95,70,65,70]}

In [134]:
a

{'x': [95, 85, 80, 70, 60], 'y': [85, 95, 70, 65, 70]}

In [135]:
df=pd.DataFrame(a)

In [136]:
df

x   y
0  95  85
1  85  95
2  80  70
3  70  65
4  60  70

In [137]:
A =np.array(df)

In [138]:
A

array([[95, 85],
       [85, 95],
       [80, 70],
       [70, 65],
       [60, 70]], dtype=int64)

In [139]:
M= np.mean(A.T,axis=1)
M

array([78., 77.])

In [140]:
C= A-M
C

array([[ 17.,   8.],
       [  7.,  18.],
       [  2.,  -7.],
       [ -8., -12.],
       [-18.,  -7.]])

In [142]:
V=np.cov(C.T)
V

array([[182.5, 117.5],
       [117.5, 157.5]])

In [143]:
COvarinace=117.5


In [153]:
var=C[:,0]**2
var

array([289.,  49.,   4.,  64., 324.])

In [154]:
sum_of_c= sum(var)


In [155]:
sum_of_c

730.0

In [157]:
m=COvarinace/sum_of_c
m

0.16095890410958905

In [159]:
#c=y_mean- mx 

y_mean=77
x_mean=78

In [161]:
c=77-m*x_mean
c

64.44520547945206

In [163]:
y=m*75+c
y

76.51712328767124

In [164]:
for i in range(df['x'].iloc[0]):
    y_pred= m*df['x']+c

In [165]:
y_pred

0    79.736301
1    78.126712
2    77.321918
3    75.712329
4    74.102740
Name: x, dtype: float64