In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from numpy import array
from numpy import mean
import math

In [2]:
x= {"x1":[-1.0,-0.5,1.0,2.0,2.5,0.0],"x2":[-0.5,0.0,2.0,0.5,-1.5,-2.0],"y":[-1.947,-0.391,6.047,4.527,1.287,-3.451]}
df=pd.DataFrame(x)
df

x1   x2      y
0 -1.0 -0.5 -1.947
1 -0.5  0.0 -0.391
2  1.0  2.0  6.047
3  2.0  0.5  4.527
4  2.5 -1.5  1.287
5  0.0 -2.0 -3.451

In [3]:
A=np.array(df)
Mean = np.mean(A.T,axis=1)
Mean

array([ 0.66666667, -0.25      ,  1.012     ])

In [4]:
x1_mean=Mean[0]
print("X1_mean : " , x1_mean) 
x2_mean=Mean[1]
print("x2_mean : ", x2_mean  )
y_mean=Mean[2]
print("Y_mean : ", y_mean  )

X1_mean :  0.6666666666666666
x2_mean :  -0.25
Y_mean :  1.0119999999999998


In [5]:
#Calculating the distance of x and y from the mean i.e x-X_mean and y-y_mean
dist= A-Mean
dist

array([[-1.66666667, -0.25      , -2.959     ],
       [-1.16666667,  0.25      , -1.403     ],
       [ 0.33333333,  2.25      ,  5.035     ],
       [ 1.33333333,  0.75      ,  3.515     ],
       [ 1.83333333, -1.25      ,  0.275     ],
       [-0.66666667, -1.75      , -4.463     ]])

In [6]:
df['x1_min_x1_mean']=dist[:,0]
df

x1   x2      y  x1_min_x1_mean
0 -1.0 -0.5 -1.947       -1.666667
1 -0.5  0.0 -0.391       -1.166667
2  1.0  2.0  6.047        0.333333
3  2.0  0.5  4.527        1.333333
4  2.5 -1.5  1.287        1.833333
5  0.0 -2.0 -3.451       -0.666667

In [7]:
df['x2_min_x2_mean']=dist[:,1]
df

x1   x2      y  x1_min_x1_mean  x2_min_x2_mean
0 -1.0 -0.5 -1.947       -1.666667           -0.25
1 -0.5  0.0 -0.391       -1.166667            0.25
2  1.0  2.0  6.047        0.333333            2.25
3  2.0  0.5  4.527        1.333333            0.75
4  2.5 -1.5  1.287        1.833333           -1.25
5  0.0 -2.0 -3.451       -0.666667           -1.75

In [8]:
df['y_min_y_mean']=dist[:,2]
df

x1   x2      y  x1_min_x1_mean  x2_min_x2_mean  y_min_y_mean
0 -1.0 -0.5 -1.947       -1.666667           -0.25        -2.959
1 -0.5  0.0 -0.391       -1.166667            0.25        -1.403
2  1.0  2.0  6.047        0.333333            2.25         5.035
3  2.0  0.5  4.527        1.333333            0.75         3.515
4  2.5 -1.5  1.287        1.833333           -1.25         0.275
5  0.0 -2.0 -3.451       -0.666667           -1.75        -4.463

In [9]:
cov=sum(dist[:,0]*dist[:,1]*dist[:,2])
print(cov)


0.6305000000000005


In [10]:
var=dist[:,0]*dist[:,0]*dist[:,1]*dist[:,1]   #Variance= Submission(x-x_mean)^2 , first square then do submission
var=sum(var)
print(var)

8.434027777777779


In [11]:
m = cov/var
print(m)
#c= y_mean- m*x_mean
c=y_mean-m*((x1_mean+x2_mean)/2)
print(c)

0.07475668999588313
0.9964256895841908


In [13]:
df["y_pred"]=m*df['x1']+m*df['x2']+c
df

x1   x2      y  x1_min_x1_mean  x2_min_x2_mean  y_min_y_mean    y_pred
0 -1.0 -0.5 -1.947       -1.666667           -0.25        -2.959  0.884291
1 -0.5  0.0 -0.391       -1.166667            0.25        -1.403  0.959047
2  1.0  2.0  6.047        0.333333            2.25         5.035  1.220696
3  2.0  0.5  4.527        1.333333            0.75         3.515  1.183317
4  2.5 -1.5  1.287        1.833333           -1.25         0.275  1.071182
5  0.0 -2.0 -3.451       -0.666667           -1.75        -4.463  0.846912

In [14]:
m*0.5+m*-1.0+c

0.9590473445862492

In [15]:
x= {"x1":[-1.0,-0.5,1.0,2.0,2.5,0.0],"x2":[-0.5,0.0,2.0,0.5,-1.5,-2.0],"y":[-1.947,-0.391,6.047,4.527,1.287,-3.451]}
df=pd.DataFrame(x)
df

x1   x2      y
0 -1.0 -0.5 -1.947
1 -0.5  0.0 -0.391
2  1.0  2.0  6.047
3  2.0  0.5  4.527
4  2.5 -1.5  1.287
5  0.0 -2.0 -3.451

In [23]:
X=df.iloc[:,[0,1]]
X

x1   x2
0 -1.0 -0.5
1 -0.5  0.0
2  1.0  2.0
3  2.0  0.5
4  2.5 -1.5
5  0.0 -2.0

In [24]:
y=df.iloc[:,2]
y

0   -1.947
1   -0.391
2    6.047
3    4.527
4    1.287
5   -3.451
Name: y, dtype: float64

In [26]:
  # Fitting Simple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X, y)

LinearRegression()

In [28]:
print( "model coeff:", regressor.coef_[0])
print ("model intercept:", regressor.intercept_)


model coeff: 1.5170710472279259
model intercept: 0.49899753593429175


In [36]:
regressor.intercept_+(regressor.coef_*0.5+regressor.coef_*-1.0)

array([-0.25953799, -0.49775893])

In [103]:
-0.25953799-0.49775893

-0.7572969199999999

# Correct way

In [37]:
x= {"x0":[1,1,1,1,1,1],"x1":[-1.0,-0.5,1.0,2.0,2.5,0.0],"x2":[-0.5,0.0,2.0,0.5,-1.5,-2.0],"y":[-1.947,-0.391,6.047,4.527,1.287,-3.451]}
df=pd.DataFrame(x)
df

#add bias as 1,1,1 in df

x0   x1   x2      y
0   1 -1.0 -0.5 -1.947
1   1 -0.5  0.0 -0.391
2   1  1.0  2.0  6.047
3   1  2.0  0.5  4.527
4   1  2.5 -1.5  1.287
5   1  0.0 -2.0 -3.451

In [41]:
X=array(x) #wrong
X

array({'x0': [1, 1, 1, 1, 1, 1], 'x1': [-1.0, -0.5, 1.0, 2.0, 2.5, 0.0], 'x2': [-0.5, 0.0, 2.0, 0.5, -1.5, -2.0], 'y': [-1.947, -0.391, 6.047, 4.527, 1.287, -3.451]},
      dtype=object)

In [39]:
X=np.matrix(x) #wrong
X

matrix([[{'x0': [1, 1, 1, 1, 1, 1], 'x1': [-1.0, -0.5, 1.0, 2.0, 2.5, 0.0], 'x2': [-0.5, 0.0, 2.0, 0.5, -1.5, -2.0], 'y': [-1.947, -0.391, 6.047, 4.527, 1.287, -3.451]}]],
       dtype=object)

In [79]:
X=np.matrix([[1,1,1,1,1,1],[-1.0, -0.5, 1.0, 2.0, 2.5, 0.0],[-0.5,0.0,2.0,0.5,-1.5,-2.0]])
X #ignore y 

matrix([[ 1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
        [-1. , -0.5,  1. ,  2. ,  2.5,  0. ],
        [-0.5,  0. ,  2. ,  0.5, -1.5, -2. ]])

# a=[a0,a1,a2]

In [80]:
#a=((x^t*x)^-1 * x^t)y

x1=X*np.transpose(X)

In [81]:
x1


matrix([[ 6.  ,  4.  , -1.5 ],
        [ 4.  , 12.5 , -0.25],
        [-1.5 , -0.25, 10.75]])

In [85]:
x2=np.linalg.inv(x1)

In [86]:
x2

matrix([[ 0.22063655, -0.07002053,  0.02915811],
        [-0.07002053,  0.10225873, -0.0073922 ],
        [ 0.02915811, -0.0073922 ,  0.09691992]])

In [63]:
x=np.matrix(x)
type(x)

numpy.matrix

In [65]:
X

matrix([[ 1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
        [-1. , -0.5,  1. ,  2. ,  2.5,  0. ],
        [-0.5,  0. ,  2. ,  0.5, -1.5, -2. ]])

In [68]:
x=array(x)
X=array(X)

In [88]:
x=x2*X
x

matrix([[ 0.27607803,  0.25564682,  0.20893224,  0.09517454,  0.00184805,
          0.16232033],
        [-0.16858316, -0.1211499 ,  0.0174538 ,  0.13080082,  0.19671458,
         -0.05523614],
        [-0.01190965,  0.03285421,  0.21560575,  0.06283368, -0.13470226,
         -0.16468172]])

In [90]:
y=np.matrix([-1.947, -0.391, 6.047, 4.527, 1.287, -3.451])
y

matrix([[-1.947, -0.391,  6.047,  4.527,  1.287, -3.451]])

In [92]:
y.T

matrix([[-1.947],
        [-0.391],
        [ 6.047],
        [ 4.527],
        [ 1.287],
        [-3.451]])

In [93]:
a=x*y.T
a

matrix([[0.49899754],
        [1.51707105],
        [1.99351294]])

In [95]:
#y=b0+b1x1+b2x2
beta_not=a[0]
beta_not

matrix([[0.49899754]])

In [98]:
beta_one=a[1]
beta_one

matrix([[1.51707105]])

In [99]:
betatwo=a[2]
betatwo

matrix([[1.99351294]])

In [100]:
y_pred=beta_not+beta_one*0.5+betatwo*-1.0

In [101]:
y_pred

matrix([[-0.73597988]])