# Eigen values, Eigen Vectors, Rank , SVD , nullity

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

#from scipy.linalg import svd

# Q3 A

In [113]:
a=np.matrix('5 8 16; 4 1 8; -4 -4 -11')

In [114]:
a

matrix([[  5,   8,  16],
        [  4,   1,   8],
        [ -4,  -4, -11]])

In [115]:
values,vectors=eig(a)
print(vectors)
print()
print(values)

[[-0.81649658+0.j         -0.31924166+0.43269619j -0.31924166-0.43269619j]
 [-0.40824829+0.j          0.78143831+0.j          0.78143831-0.j        ]
 [ 0.40824829+0.j         -0.23109832-0.2163481j  -0.23109832+0.2163481j ]]

[ 1.+0.00000000e+00j -3.+1.46298053e-15j -3.-1.46298053e-15j]


# Q3 B

In [111]:
a=np.matrix('8 -8 -2; 4 -3 -2; 3 -4 1')
a

matrix([[ 8, -8, -2],
        [ 4, -3, -2],
        [ 3, -4,  1]])

In [112]:
values,vectors=eig(a)
print(vectors)
print()
print(values)

[[-0.74278135 -0.81649658 -0.80178373]
 [-0.55708601 -0.40824829 -0.53452248]
 [-0.37139068 -0.40824829 -0.26726124]]

[1. 3. 2.]


# Q4 A

In [49]:
a=np.matrix([-1,2,2])
aa

matrix([[-1,  2,  2]])

In [50]:
a.T

matrix([[-1],
        [ 2],
        [ 2]])

In [51]:
U, s, VT = svd(a.T)

In [52]:
U

array([[-0.33333333,  0.66666667,  0.66666667],
       [ 0.66666667,  0.66666667, -0.33333333],
       [ 0.66666667, -0.33333333,  0.66666667]])

In [44]:
s

array([3.])

In [45]:
VT

array([[1.]])

# Q4 B

In [3]:
x= {"x":[1,2,3,4,5],"y":[2,4,5,4,5]}
x

{'x': [1, 2, 3, 4, 5], 'y': [2, 4, 5, 4, 5]}

In [4]:
df=pd.DataFrame(x)
df

x  y
0  1  2
1  2  4
2  3  5
3  4  4
4  5  5

In [5]:
A=np.array(df)

In [6]:
Mean = np.mean(A.T,axis=1)
Mean

array([3., 4.])

In [7]:
x_mean=Mean[0]
print("X_mean : " , x_mean) 
y_mean=Mean[1]
print("Y_mean : ", y_mean  )

X_mean :  3.0
Y_mean :  4.0


In [8]:
#Calculating the distance of x and y from the mean i.e x-X_mean and y-y_mean
dist= A-Mean
dist

array([[-2., -2.],
       [-1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 2.,  1.]])

In [9]:
df['x_min_x_mean']=dist[:,0]
df

x  y  x_min_x_mean
0  1  2          -2.0
1  2  4          -1.0
2  3  5           0.0
3  4  4           1.0
4  5  5           2.0

In [10]:
df['y_min_y_mean']=dist[:,1]
df

x  y  x_min_x_mean  y_min_y_mean
0  1  2          -2.0          -2.0
1  2  4          -1.0           0.0
2  3  5           0.0           1.0
3  4  4           1.0           0.0
4  5  5           2.0           1.0

In [11]:
cov=sum(dist[:,0]*dist[:,1])
cov

6.0

In [12]:
var=dist[:,0]*dist[:,0]   #Variance= Submission(x-x_mean)^2 , first square then do submission
var

array([4., 1., 0., 1., 4.])

In [13]:
var=sum(var)
var

10.0

In [14]:
m = cov/var
m

0.6

In [15]:
#c= y_mean- m*x_mean

c=y_mean-m*x_mean
c

2.2

In [16]:
df["y_pred"]=m*df['x']+c
df

x  y  x_min_x_mean  y_min_y_mean  y_pred
0  1  2          -2.0          -2.0     2.8
1  2  4          -1.0           0.0     3.4
2  3  5           0.0           1.0     4.0
3  4  4           1.0           0.0     4.6
4  5  5           2.0           1.0     5.2

In [17]:
df['E']=df['y']-df['y_pred']
df

x  y  x_min_x_mean  y_min_y_mean  y_pred    E
0  1  2          -2.0          -2.0     2.8 -0.8
1  2  4          -1.0           0.0     3.4  0.6
2  3  5           0.0           1.0     4.0  1.0
3  4  4           1.0           0.0     4.6 -0.6
4  5  5           2.0           1.0     5.2 -0.2

# Q1 A

In [3]:
a=np.matrix('1 -3 -2 4; 1 -3 1 1; 0 0 -1 1')
a

matrix([[ 1, -3, -2,  4],
        [ 1, -3,  1,  1],
        [ 0,  0, -1,  1]])

In [4]:
a.shape[1]

4

In [68]:
rank= np.linalg.matrix_rank(a)
rank

2

In [10]:
a.shape[1]

4

In [71]:
#nullity + rank = no. of features
#nullity = no.of fea. - rank

nullity= a.shape[1]- rank
nullity

2

In [74]:
from sympy import Matrix

A = [[1,-3,-2,4], [1,-3,1,1], [0,0,-1,1]]

A = Matrix(A)

# Number of Columns
NoC = A.shape[1]

# Rank of A
rank = A.rank()

# Nullity of the Matrix
nullity = NoC - rank

print("Nullity : ", nullity)
print("Rank : ",rank)

Nullity :  2
Rank :  2


# Q2 B

In [18]:
data={'x':[4,8,13,7],'y':[11,4,5,14]} 
data

{'x': [4, 8, 13, 7], 'y': [11, 4, 5, 14]}

In [19]:
df=pd.DataFrame(data)

In [21]:
A=np.array(df)
A

array([[ 4, 11],
       [ 8,  4],
       [13,  5],
       [ 7, 14]], dtype=int64)

In [22]:
# calculate the mean of each column
M = mean(A.T, axis=1)
print("Mean of Columns")
print(M)

Mean of Columns
[8.  8.5]


In [24]:
# center columns by subtracting column means
C = A - M
print(C)

[[-4.   2.5]
 [ 0.  -4.5]
 [ 5.  -3.5]
 [-1.   5.5]]


In [27]:
print("calculate covariance matrix of centered matrix")
V = cov(C.T)
print(V)

calculate covariance matrix of centered matrix
[[ 14. -11.]
 [-11.  23.]]


In [31]:
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print()
print(values)

[[-0.83025082  0.55738997]
 [-0.55738997 -0.83025082]]

[ 6.61513568 30.38486432]


In [32]:
P = vectors.T.dot(C.T)
print(P.T)

[[ 1.92752836 -4.30518692]
 [ 2.50825486  3.73612869]
 [-2.20038921  5.69282771]
 [-2.23539401 -5.12376947]]
